### PR TITLE
(fix) O3-2840: Download button and TableToolbarSearch component shouldn't overlap

### PR DESCRIPTION
**Pull request by subhamkumarr**
## Requirements
- [X] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [X] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [X] My work includes tests or is validated by existing tests.

## Summary
The download button and search icon do not overlap with the table body.

#### Before changes:

https://github.com/openmrs/openmrs-esm-patient-management/assets/99977240/98dc51de-4268-4f5b-99e8-01bc02cc201d

#### After Changes:
https://github.com/openmrs/openmrs-esm-patient-management/assets/99977240/57b04e38-980c-4c16-acc4-0f0c7ce2f61c

## Related Issue
https://openmrs.atlassian.net/jira/software/c/projects/O3/issues/O3-2840?filter=recentlyviewed

### CODE REVIEW

**Comment by subhamkumarr** [comment]
@denniskigen Could you please review this PR.

**Comment by denniskigen** [comment]
Could you please resolve the conflicts, @subhamkumarr?

**Comment by vasharma05** [comment]
You did 2 different kinds of zoom here, the 1st video had `ctrl+` and the second was actually the screen zooming, which is done by the touchpad. The first one changes the layout, the second one is just zooming in using touchpad.

**Comment by subhamkumarr** [comment]
@vasharma05 which video should I update `After change` or `before change`?

**Comment by subhamkumarr** [comment]
@denniskigen  I resolved the merge conflicts.

**Review by denniskigen — APPROVED** [review]

**Comment by denniskigen** [comment]
Thanks, @subhamkumarr. I've tweaked the approach slightly. Hope you don't mind.

**Pull request merged**
