### PR TITLE
(fix) O3-2174: Fix stacking context in the appointments widget search overlay 

### PR DESCRIPTION
**Pull request by jwnasambu**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).
- [x] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
I adjusted the `z-index` from `z-index: 1`to `z-index: 3` in the tabletOverlay in the Appointment application.

## Screenshots

https://github.com/openmrs/openmrs-esm-patient-management/assets/33891016/8957451a-0cb6-4562-a112-67141f0c7961

*None.*

## Related Issue

https://issues.openmrs.org/browse/O3-2174

## Other

*None.*

### CODE REVIEW

**Comment by jwnasambu** [comment]
@ibacher, @Jexsie kindly feel free to review my PR at your convinient time please!

**Review by Jexsie — APPROVED** [review]
Thanks @jwnasambu

**Comment by Jexsie** [comment]
Would you please add this PR to the ticket too

**Comment by jwnasambu** [comment]
@Jexsie its fixed. Thanks

**Review by denniskigen — APPROVED** [review]
LGTM. Thanks, @jwnasambu!

**Pull request merged**
