### PR TITLE
(feat) Add optional `Date appointment issued` field to the appointment form

### PR DESCRIPTION
**Pull request by ojwanganto**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary

This PR adds an optional date field that captures the date when an appointment was issued.

## Screenshots

[Screencast from 05-30-2024 06:00:34 PM.webm](https://github.com/openmrs/openmrs-esm-patient-management/assets/2161877/dedbe5ee-3516-4da5-b68c-3def5e7717ca)

Payload:
image

Response:
image

## Related Issue
https://openmrs.atlassian.net/browse/O3-3343
https://bahmni.atlassian.net/browse/BAH-3869

### CODE REVIEW

**Review by mogoodrich — COMMENTED** [review]
This generally looks good to me, though assumedly we have to wait until the Bahmni PR gets merged in before merging this?  I see the E2E tests are failing, but that could be the reason for this.

I like the terminology used for the end user, "Date appointment issued", though we likely have to assess if the user is confused about what this date means (vs appointment date).

**Review by donaldkibet — APPROVED** [review]
Thanks @ojwanganto LGTM

**Comment by ojwanganto** [comment]
@jayasanka-sack - I still see the e2e tests failing. The backend changes required for this ticket were merged today. Kindly help me with this. Thanks

**Review by makombe — APPROVED** [review]

**Comment by jayasanka-sack** [comment]
I've enabled traces, it looks like there's a runtime error. Could you please [download the report](https://o3-docs.openmrs.org/docs/frontend-modules/testing#view-test-reports-from-github-actions--bamboo) from [here](https://github.com/openmrs/openmrs-esm-patient-management/actions/runs/9399499048) and open the traces? It will help to debug the issue.

**Comment by jayasanka-sack** [comment]
There's a runtime error and it is silenced by this line:


https://github.com/openmrs/openmrs-esm-patient-management/blob/e0b71d7bd09fcf5da2c296d7c882f236e80f4fc0/packages/esm-appointments-app/src/form/appointments-form.component.tsx#L370

Screenshot 2024-06-06 at 16 58 09

**Comment by ojwanganto** [comment]
Thanks @jayasanka-sack. Let me have a look

**Comment by denniskigen** [comment]
@chibongho is this good to go?

**Review by chibongho — APPROVED** [review]
LGTM.

**Comment by denniskigen** [comment]
Wait! Don't merge yet.

**Comment by denniskigen** [comment]
Good to go!

**Pull request merged**
