### PR TITLE
O3-2930: Add date of birth to patient details in Appointments Module

### PR DESCRIPTION
**Pull request by sparsh989**
This PR consists of adding Date of Birth to the Appointments page. A hook `usePatientDetails` has been implemented to fetch the required details from the REST API endpoint `\person`.
Telephone Number attribute can also be added easily by extending this work once the backend changes are sorted out.
screenshot
[**Related issue**](https://openmrs.atlassian.net/browse/O3-2930?focusedCommentId=139622&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-139622)

### CODE REVIEW

**Comment by TamtoMefotieJunie** [comment]
i think it is good as such

**Review by mogoodrich — APPROVED** [review]
LGTM, thanks @sparsh989 !  Let me know if you need me to merge this in for you.

**Comment by mogoodrich** [comment]
Actually, can you make sure you add "(feature)" at the front of the commit message when merging? Thanks!

**Comment by sparsh989** [comment]
> Actually, can you make sure you add "(feature)" at the front of the commit message when merging? Thanks!

Sure thanks a lot for the help!

**Comment by sparsh989** [comment]
> LGTM, thanks @sparsh989 ! Let me know if you need me to merge this in for you.

Actually, I don't have merge access. So, it would be a great help if you could take this step. Thanks!

**Comment by mogoodrich** [comment]
will do @sparsh989 !

**Pull request merged**
