### PR TITLE
(fix)Back to search results button

### PR DESCRIPTION
**Pull request by jwnasambu**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary

I fixed the `Back button` to take the user back to search results. To achieve this, I modified the onClick handler of the Back button to call the toggleSearchType function with the `SEARCH_RESULTS` mode. 

## Screenshots

https://github.com/openmrs/openmrs-esm-patient-management/assets/33891016/dba3296f-7af5-4704-ae8b-8d2e87475733

### CODE REVIEW

**Comment by jwnasambu** [comment]
@mseaton I was just playing around with code after your discussion on this ticket https://openmrs.atlassian.net/browse/O3-2467 and after reaching out @samsino during the coffee break.

**Review by mseaton — CHANGES_REQUESTED** [review]
Thanks @jwnasambu .  A few things :  
1. The behavior is supposed to be that if you are in the full visit form, but you got here from the list of appointments, then the current feature remains, but if you go into the full visit form without first going to the list of appointments, then it needs to go back to search results.
2. In your screencast, it doesn't actually look like the search results that you go back to is working.  Does the search you go back to actually render as expected?

**Comment by jwnasambu** [comment]
@mseaton Thanks so so much for your guidance its what I needed most.Let me kick start from there. Once again, am so so grateful for your help.

**Comment by sam-sny** [comment]
Nice one @jwnasambu, Thanks for hoping on this, Changes need to me made on the extension to sort this out

**Comment by brandones** [comment]
Fixed in https://github.com/openmrs/openmrs-esm-patient-management/pull/1168 . Tested and closed by Fiona.

**Pull request closed without merging**
