### PR TITLE
feat: O3-946: Disable unique manually entered patient identifiers in offline mode

### PR DESCRIPTION
**Pull request by manuelroemer**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [x] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

Prevents the user from selecting/editing manually entered patient identifiers while in offline mode. See the associated ticket for the rationale.

## Screenshots

Offline:
grafik

## Related Issue

https://issues.openmrs.org/browse/O3-946

## Other

*None.*

### CODE REVIEW

**Comment by manuelroemer** [comment]
@vasharma05 Would love to have your review for this as you arguably know most about the patient identifiers in the patient registration.

**Comment by vasharma05** [comment]
Hey @manuelroemer! Thank you for calling me in here. It just feels like a pleasure to me.

Can you please tell me more about the `uniquenessBehaviour` variable? I'm not aware of it.
Thanks!

**Comment by manuelroemer** [comment]
@vasharma05 Sure! I'm using the attribute to identify which identifiers must be unique. These could lead to conflicts when entered manually while offline during syncing. The documentation for these is lacking - I myself used [these code comments](https://github.com/openmrs/openmrs-core/blob/e3fb1ac0a052aeff0f957a150731757dd319693b/api/src/main/java/org/openmrs/PatientIdentifierType.java#L41) as reference.

To be honest, now that I look at them again, I should probably also include the `LOCATION` value (though I'm not sure if this is used? I haven't yet seen an identifier bound to a location..).

**Review by vasharma05 — COMMENTED** [review]
P.S. Since you didn't make any changes to this line, I was not able to request change in here. Secondly, it's my first time, so pardon any inconvenience.

In file packages/esm-patient-registration-app/src/patient-registration/field/id/identifier-selection-overlay.tsx Line 42

I have a request to make some changes here:

image

Let me put up the cases:

Case 1: The identifier already had a source selected before by the user.
`identifier?.source` assigns the already source selected
Works in both offline and online modes.

Case 2: The identifier's source was not selected before

Case 2. a: The app is online
It assigns the first source to the respective identifier

Case 2. b: The app is offline
It assigns the source which has autoGeneration and manualEntry is disabled in it.

I hope you get my point.

**Comment by manuelroemer** [comment]
Thanks @vasharma05, that's exactly the type of feedback I had hoped to receive! I made the change and fixed some other issues I found during testing.

**Review by FlorianRappl — APPROVED** [review]

**Pull request merged**
