### PR TITLE
(feat) O3-3818: Add clinical forms workspace to Ward app sidebar

### PR DESCRIPTION
**Pull request by usamaidrsk**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary

This PR adds clinical forms workspace on the patient ward. This it to eliminate where a user has to go to and fro from the patient chart to the ward app so as to fill forms.

## Screenshots

forms-list

## Related Issue

https://openmrs.atlassian.net/browse/O3-3818

### CODE REVIEW

**Review by mogoodrich — APPROVED** [review]
@usamaidrsk  this looks good to me, but I will defer to people with more O3/workspace experience...

**Review by chibongho — COMMENTED** [review]
Looks good to me, but I think others with more knowledge of the workspace should review.

**Comment by brandones** [comment]
We should certainly be thinking about ways to simplify all this clinical forms stuff as it develops, but this seems reasonable enough for now.

**Comment by mogoodrich** [comment]
Thanks @brandones !  @usamaidrsk  this still isn't working fully, but I made a little discovery while test again, see: 
https://openmrs.atlassian.net/browse/O3-3818

**Pull request merged**
