### PR TITLE
O3-2549 Scheduled Appointments doesn't update immediately upon saving…

### PR DESCRIPTION
**Pull request by CynthiaKamau**
… new Appointment

## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
- Mutate appointment list after adding new appointment 

## Screenshots
https://www.loom.com/share/c6a18759eea744c9b271a5ca58006e7c?sid=6e3c8bb3-9e2f-4a5c-b150-a1e9d6f08b95

*None.*

## Related Issue

*None.*

## Other

*None.*

### CODE REVIEW

**Review by njiddasalifu — CHANGES_REQUESTED** [review]
hey @CynthiaKamau  kindly update the title of the PR to follow the PR naming. You can check in the PRs for example. 
Also in the PR summary be clear of what you have done and remove redundacy. then include screenshots of the working locally

**Review by njiddasalifu — CHANGES_REQUESTED** [review]
hey @CynthiaKamau  kindly update the title of the PR to follow the PR naming. You can check in the PRs for example. 
Also in the PR summary be clear of what you have done and remove redundacy. then include screenshots of the working locally

**Review by njiddasalifu — CHANGES_REQUESTED** [review]
hey @CynthiaKamau  kindly update the title of the PR to follow the PR naming. You can check in the PRs for example. 
Also in the PR summary be clear of what you have done and remove redundacy. then include screenshots of the working locally

**Review by njiddasalifu — CHANGES_REQUESTED** [review]
hey @CynthiaKamau  kindly update the title of the PR to follow the PR naming. You can check in the PRs for example. 
Also in the PR summary be clear of what you have done and remove redundacy. then include screenshots of the working locally

**Review by njiddasalifu — CHANGES_REQUESTED** [review]
hey @CynthiaKamau  kindly update the title of the PR to follow the PR naming. You can check in the PRs for example. 
Also in the PR summary be clear of what you have done and remove redundacy. then include screenshots of the working locally

**Review by njiddasalifu — APPROVED** [review]
Looks working well now. 
maybe someone else can aprove too. 
@CynthiaKamau  consider adding the ticket link under related issue.

**Comment by mogoodrich** [comment]
Thanks @njiddasalifu !  @CynthiaKamau  I'd say let's go ahead and merge!

**Pull request merged**
