### PR TITLE
(fix) O3-3171 follow-up to fix Replace overlays in the Appointments app

### PR DESCRIPTION
**Pull request by kb019**
## Requirements

- [X] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [X] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary
This PR is with respect to the issue encountered [here](https://github.com/openmrs/openmrs-esm-patient-management/pull/1133#issuecomment-2135338300).

### CODE REVIEW

**Comment by kb019** [comment]
Hi @mogoodrich and @brandones , one of the issue was there was a WorkspaceOverlay in esm-home-module with context key of "home" (like \<WorkspaceOverlay contextKey="home"/>).So it was present in both appointments and home page , as appointments page had url containing home like "...home/appointments".So removed the overlay in appointments.

Also i encountered a weird error. When i presses on the recurring appointement button,the top part of workspace gets cutoff and there is a white space created at  the bottom. But when i remove the overflow property from workspace usind devtools,it seems to work fine.Please have a look at the video below.
[OpenMRS - Personal - Microsoft_ Edge 2024-05-29 17-14-35.webm](https://github.com/openmrs/openmrs-esm-patient-management/assets/115476530/b877415f-0b22-48c9-8c35-7a4c0ac7934b)

**Comment by brandones** [comment]
Thanks @kb019 ! Yes, please fix the issues with the recurring appointment button.

**Comment by mogoodrich** [comment]
Thanks @kb019 !  Defer to @brandones  on this fix and how to best handle the multiple "home" overlays...

**Comment by brandones** [comment]
@mogoodrich  Yeah adding the additional overlay instance to the appointments app was a mistake; the overlay only should exist once per page. Here, the overlay is hosted by the home page app.

**Review by mogoodrich — APPROVED** [review]
Thanks @kb019 ... if @brandones  things this looks good to me, I'm happy to merge.

**Comment by brandones** [comment]
There's still the problem @kb019 showed in the video with the styling. I'm happy to have this PR in but it would be great to see that addressed.

**Comment by kb019** [comment]
Hi @brandones ,once we pull the latest changes from esm-framework (yarn up openmrs@next @openmrs/esm-framework@next), there should'nt be any issue with the stylings. Thank you.

**Comment by mogoodrich** [comment]
yes, thanks @kb019 ... from my testing, it appears the styling issues have been fixed but @brandones  let us know if you notice otherwise

**Pull request merged**
