### PR TITLE
O3-1205: changed Patient list tooltip position to the left

### PR DESCRIPTION
**Pull request by abertnamanya**
**Issue:** https://issues.openmrs.org/browse/O3-1205

**Work done:**

Changed the patient list button tooltip on the side menu to the left

patientList png

### CODE REVIEW

**Comment by denniskigen** [comment]
@abertnamanya Please include screenshots for UI work

**Comment by abertnamanya** [comment]
> @abertnamanya Please include screenshots in your PR description for UI work.

Hello @denniskigen  and @ZacButko please review this PR

**Comment by denniskigen** [comment]
Looks like this already got fixed [here](https://github.com/openmrs/openmrs-esm-patient-management/pull/154).

**Comment by abertnamanya** [comment]
> Looks like this already got fixed [here](https://github.com/openmrs/openmrs-esm-patient-management/pull/154).

Yeah, I have just seen that it was done. @denniskigen You could close this PR

**Comment by denniskigen** [comment]
Closed in favour of https://github.com/openmrs/openmrs-esm-patient-management/pull/154.

**Pull request closed without merging**
