### PR TITLE
(chore) Bump Playwright version

### PR DESCRIPTION
**Pull request by jayasanka-sack**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
The purpose of this PR is to upgrade playwright version.

## Screenshots

*None.*

## Related Issue

*None.*

## Other

*None.*

### CODE REVIEW

**Review by vasharma05 — APPROVED** [review]
LGTM!

**Comment by vasharma05** [comment]
Can you please look into the failing bundle size report?

**Comment by denniskigen** [comment]
About the failing build, you need to commit your lockfile as well.

**Comment by jayasanka-sack** [comment]
I see. I didn't notice it.

**Pull request merged**
