### PR TITLE
Enabled Pressing Enter key to select the Radio button

### PR DESCRIPTION
**Pull request by Josephkagimu1**
### Summary 
Pressing tab allows you move through the form,
We need to be able to select the radio button by pressing Enter key .
When your in gender field you will just press Enter key and the radio button is selected ,
then proceed .

## Screenshots
Screen Shot 2022-04-07 at 8 17 17 AM

### CODE REVIEW

**Comment by jwnasambu** [comment]
@Josephkagimu1 kindly include the ticket Id on your commit and a clear description of what you changed. Besides, the ticket link should be included on this PR to help the reviewer confirm the expected output.

**Comment by Josephkagimu1** [comment]
@jwnasambu  Am to provide the necessary links, but whats up with my PR ? , I see  `Merging is blocked`.  #148

**Comment by Josephkagimu1** [comment]
kIndly Review @donaldkibet  @denniskigen

**Comment by Josephkagimu1** [comment]
Hei @brandones, @jonathandick , @ZacButko, have a look, review

**Comment by ZacButko** [comment]
As mentioned in [O3-1244](https://issues.openmrs.org/browse/O3-1244) this work does not need to be done. Selection of a radio item is already accessible with the Space and Keyboard Arrow keys

**Pull request closed without merging**
