### PR TITLE
(feat)O3-2573: Using Snackbar in service-queue-app

### PR DESCRIPTION
**Pull request by njiddasalifu**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. 
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).
- [x] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
Implemented the use of showSnackbar in esm-service-queue. This is done by replacing the showToast to showSnackbar.

## Screenshots

  Pending screenshots

## Related Issue

https://openmrs.atlassian.net/browse/O3-2631

### CODE REVIEW

**Comment by njiddasalifu** [comment]
Hey @hadijahkyampeire here is the PR for the snackbar imple in esm-service-queue. You can review and let me know if ther are modifications to be made. I will update the Screenshot in due time

**Review by hadijahkyampeire — COMMENTED** [review]
Thanks @njiddasalifu this looks good, just a small mispelling.

**Comment by hadijahkyampeire** [comment]
@njiddasalifu would you please fix the linting error, that is the same one Henry is facing on his PR.

**Comment by njiddasalifu** [comment]
Hello @hadijahkyampeire, @vasharma05 , @denniskigen  , I have updated the fix, you can review and merge.

**Pull request merged**
