### PR TITLE
BREAKING: Rename `outpatient-app` to `service-queues`

### PR DESCRIPTION
**Pull request by donaldkibet**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

Renamed the `Outpatient` app to `Service Queues` to better communicate the functionality of the application. Every thing else remains the same

cc @gracepotma @denniskigen @makombe @CynthiaKamau @jecihjoy What do you guys think?

## Screenshots

*None.*

## Related Issue

*None.*

## Other

*None.*

### CODE REVIEW

**Comment by makombe** [comment]
@donaldkibet I think the renaming is good. Make sense to me. Please resolve the conflicts, thanks.

**Review by CynthiaKamau — COMMENTED** [review]
Thanks @donaldkibet for this. Kindly fix the conflicts

**Review by CynthiaKamau — APPROVED** [review]

**Comment by denniskigen** [comment]
@donaldkibet could you open a corresponding PR updating the [spa-build-config](https://github.com/openmrs/openmrs-distro-referenceapplication/blob/7a5c07f47fcfedaf9bbf78bbfddce6b64e4295fb/frontend/spa-build-config.json#L4) file?

**Comment by denniskigen** [comment]
Also, I've marked this as BREAKING because it necessitates and update to module lists for all downstream users of the RefApp to account for this change.

**Pull request merged**
