### PR TITLE
feat) O3-3348: Allow Checking in to appointments even if there's already an active v…

### PR DESCRIPTION
**Pull request by lucyjemutai**
…isit

## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary

https://openmrs.atlassian.net/browse/O3-3348

I refactored the CheckInButton component to simplify logic and support showing the button even with an active visit, based on a config option. This eliminates the need for a custom check-in form.

### CODE REVIEW

**Comment by lucyjemutai** [comment]
The changes don't introduce any visible differences on the UI. The work had been partially done -->https://github.com/openmrs/openmrs-esm-patient-management/pull/1165/

**Comment by mogoodrich** [comment]
Thanks @lucyjemutai !  Let me refresh my memory on this ticket and then I will review...

**Comment by mogoodrich** [comment]
@lucyjemutai  can you remind me where this appears in the UI?

**Comment by lucyjemutai** [comment]
@mogoodrich So, this ticket was to allow the `check in`  even when a patient has active visit. . The work had been partially done  and for this pr there is no visible differences on the UI.

**Comment by ojwanganto** [comment]
> @mogoodrich So, this ticket was to allow the `check in` even when a patient has active visit. . The work had been partially done and for this pr there is no visible differences on the UI.

I thought it is the check-in process that starts a visit. How then do we have check-in for already checked in patients?

**Comment by mogoodrich** [comment]
Thanks @lucyjemutai !  I'm a little underwater now with work right now and need to refresh my memory on my initial requirements for this, but I hope to get to it soon.

**Comment by mogoodrich** [comment]
@lucyjemutai, unfortunately.  I don't think we are ready for this yet, I have have updated the ticket with more thoughts on the design.  Not sure if this is a priority for others, we (PIH) have served our use case by creating a custom HTML Form Entry check-in form).  I am going to close this out, but thanks so much!

**Comment by lucyjemutai** [comment]
@mogoodrich Noted, thanks!

**Pull request closed without merging**
