### PR TITLE
03-2497:(feat)Home page left nav links should support i18n

### PR DESCRIPTION
**Pull request by sherrif10**
## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Screenshots

*None.*

## Related Issue

*None.*

## Other

*None.*

### CODE REVIEW

**Comment by sherrif10** [comment]
Hello @denniskigen @ibacher . This Pr has it's child to ticket from openmrs esm home which will render all this translation. Which I will share here. Meanwhile. Let me know what your suggestions are ?

**Review by njiddasalifu — COMMENTED** [review]
@sherrif10  could you add screenshots of the work done too.

**Comment by ibacher** [comment]
@sherrif10 There's no way that this actually works. Please review the code linked in the PR. It's supposed to guide you to how to solve the issue here.

**Comment by sherrif10** [comment]
Thanks , I Will update this ticket accordingly

**Comment by vasharma05** [comment]
Hi @sherrif10 , this is already worked and done here at #820

**Comment by sherrif10** [comment]
> Hi @sherrif10 , this is already worked and done here at #820

Alright cool , i will close this for now.

**Pull request closed without merging**
