### PR TITLE
O3-2812: Appointments: Refactoring and Code Cleanup

### PR DESCRIPTION
**Pull request by mogoodrich**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

### CODE REVIEW

**Comment by mogoodrich** [comment]
Trying to do some commits to organize the appointments ESM while not going too overboard.  The majority of the hooks in the appointments ESM appear to be in various "use*.tx" files within the "hooks" directory.  We might want to standardize tihis a bit more (it is best practice to have multiple hooks in a "use*.tx" file, but rather than going overboard I'd start  just try to centralize a  things a bit, so I refactored two resources.tx file, "appointments.resouce.ts" and 'appointments-table.ts" which basically consistedn of deleting those two files and moving the only hook within them that was used into "hooks/useAppointments"

**Review by mseaton — APPROVED** [review]
LGTM

**Review by denniskigen — APPROVED** [review]
This LGTM. Thanks, @mogoodrich.

**Comment by ibacher** [comment]
Thanks @mogoodrich!

**Pull request merged**
