### PR TITLE
(fix) O3-2505:Multiple Requests to identifiersource

### PR DESCRIPTION
**Pull request by sherrif10**
PR https://issues.openmrs.org/browse/O3-2505    cc  @dkayiwa @ibacher  @denniskigen

## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Screenshots

*None.*

## Related Issue

*None.*

## Other

*None.*

### CODE REVIEW

**Comment by ibacher** [comment]
Thanks @sherrif10, but this definitely doesn't resolve the issue in the ticket. The issue is with too many GET requests to the `/identifiersources` end point with a query string. These modifications actually do nothing to remove the pre-existing requests and just adds a new one.

**Comment by sherrif10** [comment]
Thanks @ibacher for Quick response, Let me re-try it again.

**Comment by denniskigen** [comment]
Closing in favour of a new implementation in a separate PR.

**Comment by gracepotma** [comment]
Thanks @denniskigen can you please add a link to the separate PR that handles this, to the related issue here, and close it out? https://issues.openmrs.org/browse/O3-2505 Thanks <3 (And please add the relevant O3 Release tag to the ticket too; in the FixVersion field)

**Comment by sherrif10** [comment]
Hello @gracepotma . Appologies for late responding on this ticket, However incase am not blocking anyone, i will pick it up this evening again.

**Comment by sherrif10** [comment]
Hello @denniskigen , was this fixed somewhere please you could share PR here. thanks.

**Pull request closed without merging**
