### PR TITLE
(fix) O3-3089: Appointment-details does not show the time of appointment for appointments not scheduled for today

### PR DESCRIPTION
**Pull request by mccarthyaaron**
## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Screenshots

Here is the before:

https://github.com/openmrs/openmrs-esm-patient-management/assets/121826239/31b7537d-4384-4856-95dd-132a2bf7a1d2

Here is the after:

https://github.com/openmrs/openmrs-esm-patient-management/assets/121826239/2b9fd5f9-9bba-44e6-90c1-fd7033d04d91

### CODE REVIEW

**Comment by subhamkumarr** [comment]
@mccarthyaaron Please provide the issue link, and add a description about the changes

**Comment by denniskigen** [comment]
As mentioned above, please link your ticket to an issue on Jira as indicated in the [contributing guidelines](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines), @mccarthyaaron.

**Comment by mccarthyaaron** [comment]
My apologies. Here is the link to the issue: https://openmrs.atlassian.net/browse/O3-3089

**Review by mogoodrich — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
