### PR TITLE
(fix) Fix alignment issue in appointments form

### PR DESCRIPTION
**Pull request by njiddasalifu**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. 
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

## Summary
In appointments form, we had allignment overlap. This PR addresses that and makes all fields visible.

## Screenshots
# Before 
Screenshot from 2023-11-06 23-31-20

before_appointments-form

# After 

after_appointments-form

## Related Issue

https://issues.openmrs.org/browse/O3-2548

### CODE REVIEW

**Comment by njiddasalifu** [comment]
Hello @denniskigen and @mogoodrich kindly review this PR its a simple fix.

**Review by mogoodrich — COMMENTED** [review]
I defer to @denniskigen  on the actual scss change, but I don't think we want to be changing the yarn.lock file here?

**Comment by njiddasalifu** [comment]
> I defer to @denniskigen on the actual scss change, but I don't think we want to be changing the yarn.lock file here?

Actually the changes in the yarn.lock file is as a result of trying to update my libraries due to some failing test. I used this command to update them 
yarn up openmrs @openmrs/esm-framework

**Comment by denniskigen** [comment]
Thanks for working on this, @njiddasalifu. The approach is OK, but this requires more work than that. I meant to push this [commit](https://github.com/openmrs/openmrs-esm-patient-management/commit/158ffec44a9fd0d9e6244462cb05d7120dd84907) to your branch updating the entire form to match what we have elsewhere, along with fixing the spacing and icon issues. Unfortunately, looks like I pushed to the `main` branch of this repo by mistake instead.

**Comment by denniskigen** [comment]
This is what the form looks like with those changes:

> Desktop

CleanShot 2023-11-10 at 12  45 56@2x


CleanShot 2023-11-10 at 12  46 24@2x

> Edit mode

CleanShot 2023-11-10 at 12  46 50@2x

> Tablet
CleanShot 2023-11-10 at 12  47 13@2x

**Comment by denniskigen** [comment]
Feel free to close this PR if you agree with the changes. Again, apologies for bypassing your PR.

**Comment by njiddasalifu** [comment]
> Feel free to close this PR if you agree with the changes. Again, apologies for bypassing your PR.

No problem @denniskigen Thanks

**Comment by denniskigen** [comment]
Thank you, @njiddasalifu

**Pull request closed without merging**
