### PR TITLE
(fix) O3-3787 : Refresh workspace title when clicked on new patient

### PR DESCRIPTION
**Pull request by kb019**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [x] My work includes tests or is validated by existing tests.

## Summary
I have mentioned detailed solution in this [PR](https://github.com/openmrs/openmrs-esm-core/pull/1177). For now this might be like a temporary solution.
The workspace title which was set dynamically does not updated when clicked on other patients.Putting the props which are passed to the title node as a dependency in useEffect works.
[OpenMRS - Personal - Microsoft_ Edge 2024-10-10 21-26-09.webm](https://github.com/user-attachments/assets/109330d6-b3c3-46e7-b7d0-5725a3505eda)

## Related Issue
https://openmrs.atlassian.net/browse/O3-3787

### CODE REVIEW

**Review by chibongho — APPROVED** [review]
Wow, that's it? Nice work!

**Comment by kb019** [comment]
> Wow, that's it? Nice work!

Thanks @chibongho .

**Comment by brandones** [comment]
I think this is the correct way to solve the problem.

**Comment by denniskigen** [comment]
https://react.dev/learn/preserving-and-resetting-state#option-2-resetting-state-with-a-key

**Pull request merged**
