### PR TITLE
(Chore): updated ar translation

### PR DESCRIPTION
**Pull request by Madhu-mac**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary
 - This PR fixes all the arabic translations by converting the originally provided english words has been replaced with its corresponding arabic translation.

### CODE REVIEW

**Comment by denniskigen** [comment]
@ibacher, should these changes go to transifex instead?

**Comment by ibacher** [comment]
Yes, absolutely!

**Comment by Madhu-mac** [comment]
@ibacher I've already tested it in local Environment. Can you verify this PR

**Comment by ibacher** [comment]
@Madhu-mac Please make the appropriate changes [here](https://app.transifex.com/openmrs/openmrs-esm-patient-management/translate/#ar) instead of via a PR. This helps keep everything in sync.

**Comment by Madhu-mac** [comment]
Okay sure! @ibacher

**Pull request closed without merging**
