### PR TITLE
Deploy patient list

### PR DESCRIPTION
**Pull request by FlorianRappl**
See previous PR: https://github.com/openmrs/openmrs-esm-patient-management/pull/22

### What does this PR do?

This PR comprises of various components:
1. Modal Design
2. Fetching patient lists
3. Review changes (reviews given to #19 )
4. Implementing search for patient lists.

Design: https://app.zeplin.io/project/60d59321e8100b0324762e05/screen/60d5993c822cc112375b4379

### CODE REVIEW

**Comment by FlorianRappl** [comment]
Hi @vasharma05 can you take care of merging this properly? Sorry, the PR from Nikita was merged first (I did not notice you had a PR against another satellite branch...).

**Comment by FlorianRappl** [comment]
Hi @vasharma05 - do you have this on the radar? Thanks!

**Comment by vasharma05** [comment]
Hi Florian! I have this on the list, will be pushing the new tomorrow morning asap. Thanks!

**Comment by vasharma05** [comment]
@FlorianRappl I have cleared the merge conflicts.

**Pull request merged**
