### PR TITLE
(fix) O3-2003: display all patient lists and disable with a check those to which that patient is already added

### PR DESCRIPTION
**Pull request by Jexsie**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).
- [x] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
  - Updates the **add to list** functionality to display all patient lists, disables and check by default those to which that patient is already added, as suggested by @samuelmale in the issue below. See the thread [here](https://openmrs.slack.com/archives/CKS32D55G/p1680180392555039)
 

## Screenshots
image

image

*None.*

## Related Issue
https://issues.openmrs.org/browse/O3-2003
*None.*

## Other

*None.*

### CODE REVIEW

**Comment by Jexsie** [comment]
cc @samuelmale @vasharma05 @hadijahkyampeire @denniskigen

**Review by hadijahkyampeire — COMMENTED** [review]
This looks good, just following the convo on slack, let make those checkboxes selected by default just to let the user know that the patient is already added to those lists.

**Comment by hadijahkyampeire** [comment]
> > This looks good, just following the convo on slack, let make those checkboxes selected by default just to let the user know that the patient is already added to those lists.
> 
> Well @hadijahkyampeire, someone talked about allowing users to be able to unselect the previously selected lists. Is this also required or, I just go on with this simple logic

I think for now we can keep it unselectable i.e disabled but checked. If the request to make it checkable comes we will come back to that.

**Comment by Jexsie** [comment]
pushed updates @hadijahkyampeire

**Review by hadijahkyampeire — APPROVED** [review]
Thanks @Jexsie for this

**Pull request merged**
