### PR TITLE
(fix) O3-3088: Appointments form accepts zero as a value for the appointment duration

### PR DESCRIPTION
**Pull request by mccarthyaaron**
## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

# Summary
The duration field in the appointments form will submit when a value of 0 is given.

### CODE REVIEW

**Comment by mccarthyaaron** [comment]
Link to issue: https://openmrs.atlassian.net/browse/O3-3088

**Review by mogoodrich — APPROVED** [review]
LGTM, I will merge, thanks @mccarthyaaron !

**Comment by mogoodrich** [comment]
Oh, acutally @mccarthyaaron  can you resolve the conflicts (that I believe were introduced when I merged in O3-3085 , thanks!

**Comment by mccarthyaaron** [comment]
@mogoodrich I have pushed a commit which merged and sorted the conflicts. Could you please take a look

**Comment by mogoodrich** [comment]
Looks good, thakns @mccarthyaaron , I will merge!

**Pull request merged**
