### PR TITLE
(fix) O3-1975: Preserve video recordings and traces of failing E2E tests

### PR DESCRIPTION
**Pull request by RandilaP**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).
- [x] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
This PR adds trace and video recording functionality to the e2e tests in OpenMRS Patient Management repo, even with a single attempt run. This will help us identify and debug issues more easily by providing detailed information about the execution of the tests and visualizing errors.

## Screenshots

*None.*

## Related Issue
https://issues.openmrs.org/browse/O3-1975

## Other

*None.*

### CODE REVIEW

**Comment by RandilaP** [comment]
Could you please review this

**Comment by RandilaP** [comment]
@jayasanka-sack @anjula-sack @Piumal1999 Could you please review this

**Review by Piumal1999 — APPROVED** [review]
Good job @RandilaP 
Could you please reduce the length of the PR title? Otherwise, the commit message will get truncated.

**Review by jayasanka-sack — CHANGES_REQUESTED** [review]
Thanks @RandilaP ! Please reduce the retry count to 0 as well.

**Review by jayasanka-sack — APPROVED** [review]
Sorry. My bad. Merged the other PR.

**Pull request merged**
