### PR TITLE
(fix) Fix the translated texts having same key and different value strings

### PR DESCRIPTION
**Pull request by vasharma05**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
This PR fixes the translated texts having same key and different value strings

## Screenshots

*None.*

## Related Issue

*None.*

## Other

*None.*

### CODE REVIEW

**Comment by ibacher** [comment]
Could you fix the test failure?

**Review by denniskigen — APPROVED** [review]
LGTM. Thanks, @vasharma05.

**Comment by ibacher** [comment]
@vasharma05 Do you have some time to fix the conflicts? 

@denniskigen @gracepotma We probably need some conventions around “what makes a good translation key” because `errorMessage` (removed here) is not too useful. Any thoughts? (It’s a bit hard)

**Review by ibacher — APPROVED** [review]

**Comment by denniskigen** [comment]
I recall @brandones once said he knew someone who might be interested in reviewing our translation keys and strings. Might that still be the case, Brandon?

**Comment by brandones** [comment]
I have no recollection :(

**Pull request merged**
