### PR TITLE
O3-3030 service queues: fix NPE in mapVisitQueueEntryProperties

### PR DESCRIPTION
**Pull request by chibongho**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary

Previous commit introduce an NPE in `mapVisitQueueEntryProperties`. Fixing it by removing an unused field in `MappedVisitQeueEntry`.

### CODE REVIEW

**Review by mseaton — COMMENTED** [review]
@chibongho - this isn't the fix I was expecting.  Are these encounters not needed / used anywhere?

**Comment by makombe** [comment]
@chibongho Thanks for the fix. I think there is also another place where `encounterProvider` was being referenced that was failing as well. Not sure if this will address the same as well

**Comment by makombe** [comment]
you can as well do a custom representation to all that you need , the use of default rep seems to leave other out some properties being mapped

**Comment by makombe** [comment]
> I don't see that field being used anywhere. If we expect to need it later I can change this to fix it via the `v=` param instead.

@chibongho please check here https://github.com/openmrs/openmrs-esm-patient-management/blob/0b0fbae1d7c2d701204ae3f0b1a211195bdb4d78/packages/esm-service-queues-app/src/active-visits/active-visits-table.resource.ts#L86

**Comment by makombe** [comment]
and here as well https://github.com/openmrs/openmrs-esm-patient-management/blob/0b0fbae1d7c2d701204ae3f0b1a211195bdb4d78/packages/esm-service-queues-app/src/hooks/useQueueEntries.ts#L5  some of the properties we are mapping are not being returned. Thanks

**Comment by chibongho** [comment]
ok, I changed the `v=` param for useQueueEntries to includes the encounters (and its fields) in the visit object. I can't find usage of `MappedVisitQueueEntry.encounters` anywhere but I'm keeping it just in case. (I believe most if not all code paths use `queueEntry.visits.encounters` now)

@makombe Where is the `encounters` field being used? I see `Visit.encounters` being using in [current-visit-details.component.tsx(https://github.com/openmrs/openmrs-esm-patient-management/blob/main/packages/esm-service-queues-app/src/current-visit/visit-details/current-visit-details.component.tsx) but I haven't been able to figure out how to properly populate test data to test it. I tried adding a visit note but the encounterType got saved as "Consultation" instead. Let me know of any test scenarios you'd like me to go through. thanks.

**Review by denniskigen — APPROVED** [review]
LGTM, @chibongho. Curious to know which property that was.

**Review by donaldkibet — APPROVED** [review]
Thanks @chibongho LGTM

**Review by makombe — APPROVED** [review]
Thanks @chibongho LGTM. I will merge we test it further

**Pull request merged**
