### PR TITLE
(fix) Properly handle focus and blur states for address hierarchy fields

### PR DESCRIPTION
**Pull request by vasharma05**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).
- [x] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
This PR fixes the issue of address Hierarchy field's focus and blur not showing/ hiding entries correctly.

## Screenshots

https://github.com/openmrs/openmrs-esm-patient-management/assets/51502471/c0f8fb26-0bfd-4e2c-ba1e-eeadb089d1ba

## Related Issue

*None.*

## Other

*None.*

### CODE REVIEW

**Comment by denniskigen** [comment]
How can I replicate this issue, @vasharma05?

**Comment by vasharma05** [comment]
Hi @denniskigen !
You can try using the address hierarchy on the patient registration and check if the entries for each field are showing when clicked and hiding when clicking outside or pressing tab.
Thanks!

**Comment by denniskigen** [comment]
Thanks for the video. Very handy.

**Review by denniskigen — APPROVED** [review]
Thanks for the fix, @vasharma05!

**Pull request merged**
