### PR TITLE
(fix) O3-2756: Fix inline dropdown rendering in appointments and service queues headers

### PR DESCRIPTION
**Pull request by subhamkumarr**
## Requirements

- [X] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

This PR fixes various aspects of how hinline dropdowns get rendered in the Appointments and Service Queues [page headers](https://zeroheight.com/23a080e38/p/8358ed-page-header). Specifically, both of these dropdowns use the [inline](https://react.carbondesignsystem.com/?path=/story/components-dropdown--inline) variant of the Carbon dropdown component. Presently, the following issues exist with those dropdowns:

- The default behaviour for the inline dropdown component is that clicking the label triggers the display of options in the dropdown panel.

	https://github.com/openmrs/openmrs-esm-patient-management/assets/8509731/a865c56f-cb09-4a47-b4aa-57ce07cbf667

  The inline dropdown in the Service Queues page header does not respect this behaviour because it doesn't specify a label using the `titleText` prop. Instead it defines a separate label using the `<label>` element. 

-  Both dropdowns content renders beyond the bounds of the parent element. 

    https://github.com/openmrs/openmrs-esm-patient-management/assets/8509731/9591fd2a-ebc6-41c4-85bc-d224fb0baedb

This PR fixes the first issue by removing the label element and using the `titleText` prop instead to set a label for the inline dropdown. It also fixes the second issue by introducing a workaround that effectively 'flips' the inline dropdown's content to the left. In lieu of a proper solution for aligning dropdowns, we could eventually end up generalizing this workaround into a custom component in the style guide.

## Related Issue

https://openmrs.atlassian.net/browse/O3-2756

### CODE REVIEW

**Comment by subhamkumarr** [comment]
@vasharma05 @sherrif10 Could you please review my PR.

**Comment by subhamkumarr** [comment]
@vasharma05 sir could you please review my PR

**Comment by Vijaykv5** [comment]
@subhamkumarr I'm actually not sure! I worked on an issue in Service queue earlier #924 
But for me , it looks file for my side as there is no drop down issue while clicking on view. 
May you could tell me how to reproduce this issue?

**Comment by subhamkumarr** [comment]
@Vijaykv5 The issue is not in the `service queue` It is in the `Appointment` section.

**Comment by subhamkumarr** [comment]
@denniskigen  could you please review my pr

**Review by Pradipram — APPROVED** [review]
lgtm

**Review by denniskigen — COMMENTED** [review]
Thanks for looking into this, @Pradipram. 

So, the behaviour of the Carbon Dropdown component is described [here](https://react.carbondesignsystem.com/?path=/story/components-dropdown--inline). You'll note that the behaviour is such that clicking on the label triggers the dropdown and launches the dropdown panel:

https://github.com/openmrs/openmrs-esm-patient-management/assets/8509731/a865c56f-cb09-4a47-b4aa-57ce07cbf667

So in that sense, I'm not sure that the currently implemented behaviour is incorrect.

**Comment by subhamkumarr** [comment]
@denniskigen Okay, I understand, but there is a dissimilarity in the design pattern. For example, in the `Appointment` section, clicking the `View` dropdown displays options. However, in the `Service queues` section, the dropdown should also be displayed when clicking on `view` but the dropdown item is not appearing. it's only displaying on clicking on the `All`.

https://www.loom.com/share/ce57d67692e94daf8d97f3f5536a7089?sid=0bfeac6f-06a5-47db-aab2-fe685da03c51

**Comment by denniskigen** [comment]
@subhamkumarr, that's because the inline dropdown in the service queues app isn't wired up correctly: 

- It uses a `<label>` tag instead of the inline dropdown's `titleText` prop
- It's missing an `aria-label` (so screen readers know what the dropdown does)
- It's missing a `label` prop

Feel free to address these if you'd like.

**Comment by subhamkumarr** [comment]
@denniskigen  I have resolved the issue in `service queues`. Now on clicking on the `view` dropdown item is displayed.
https://www.loom.com/share/54ea2cead3db49a1928af742cbf53220?sid=8ce8d2f1-e202-41be-8bb7-35fb75550872

**Comment by pirupius** [comment]
@subhamkumarr i've noticed your screen recordings always shift the page when the dropdown is open is this because of the screen/window size or an effect that was introduced by your PR? I've checked dev3 and that effect isn't there.

**Comment by subhamkumarr** [comment]
@pirupius but in today coffee meet i have shown this issue to @denniskigen he is also facing the same.

**Comment by subhamkumarr** [comment]
@denniskigen do I need to make any changes? according to me, it's working fine for me.

**Comment by denniskigen** [comment]
I'm trying to look into the dropdown alignment (how it gets cut off the screen). I'd like to fix it within this PR.

**Comment by subhamkumarr** [comment]
@denniskigen Okay

**Comment by denniskigen** [comment]
Unfortunately, it looks like we won't be getting an `align` or `flipped` prop for the [Dropdown](https://react.carbondesignsystem.com/?path=/story/components-dropdown--inline) component anytime soon, as per the resolution on https://github.com/carbon-design-system/carbon/issues/7491. 

However, I've implemented a workaround to fix the issue of the dropdown's content extending beyond the bounds of its parent container. I've set a fixed width for the dropdown field and I'm hiding any content that overflows this width. Additionally, I've adjusted the position of the dropdown menu for inline display by shifting it to the left by 4rem. This provides an acceptable amount of consistent rendering regardless of content length, given the constraints. 

Please see the video below for a demonstration of how this looks in practice:

https://github.com/openmrs/openmrs-esm-patient-management/assets/8509731/a00c73aa-8afa-479a-a165-6460803cc40c

**Comment by subhamkumarr** [comment]
@denniskigen, I got it. Thanks for the beautiful explanation!

I also tried to fix the overflow from the screen by reducing the width and got a little closer. But there is unnecessary extra space.
ss

**Review by pirupius — APPROVED** [review]

**Comment by pirupius** [comment]
@denniskigen no further concerns on my side

**Comment by denniskigen** [comment]
Thanks, all.

**Pull request merged**
