### PR TITLE
(fix) O3-2711: Fix the sizing of the identifier input delete icon

### PR DESCRIPTION
**Pull request by Vijaykv5**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary
Just removed the `hasIconOnly` from button.

## Screenshots

> Before :
Screenshot 2024-01-19 at 09 11 19

> After :

Screenshot 2024-01-21 at 2 38 32 PM

## Related Issue

[O3-2711](https://openmrs.atlassian.net/browse/O3-2711)

### CODE REVIEW

**Comment by sherrif10** [comment]
Looks fine , though something small,  Can you ensure the trash icon have same size with input area.

**Comment by Vijaykv5** [comment]
> Looks fine , though something small, Can you ensure the trash icon have same size with input area.

@sherrif10 Yes the trash icon has same size over every code  no matter the size of input i.e, `size={16}`So I think that won't be a problem

**Comment by Vijaykv5** [comment]
May you revjew this PR @denniskigen

**Comment by denniskigen** [comment]
Thanks, @Vijaykv5. Because this is an icon button, we'd still need the [hasIconOnly](https://react.carbondesignsystem.com/?path=/story/components-button--icon-button) prop, so that's not the solution. The code as originally structured should work out of the box. I'm suspecting that the issue here is Carbon and not the implementation. I'll test things out with a more up to date version of the library locally later today to try and rule some things out.

**Comment by Vijaykv5** [comment]
Ok @denniskigen

**Comment by manuhabitela** [comment]
Hey guys,

Allowing myself to add something, as I checked this issue as a way to discover OpenMRS :)

The thing is the `danger--ghost` Button kind for icon-only buttons is not supported by Carbon, it's intended: https://github.com/carbon-design-system/carbon/issues/15452#issuecomment-1877537469

One easy "fix" would be to just use a `ghost` kind instead of starting to code specific styles. We'd lose the "red on hover" style but I guess it's acceptable in this case?

**Comment by manuhabitela** [comment]
As for the sizing issue that @sherrif10 mentions, I also noticed it was because if mismatched carbon versions between the esm-styleguide project and the others.

It's all explained in details in some commits I started and wanted to open PRs with after I got access to everything:

https://github.com/manuhabitela/openmrs-esm-patient-management/commit/e0e887f0adb5f9943d9f7d17984b400fb74e22ed and https://github.com/manuhabitela/openmrs-esm-patient-management/commit/67cd170fba46caa3adbb9b5e6c31a7c79bc1b142.

**Comment by rbuisson** [comment]
>We'd lose the "red on hover" style but I guess it's acceptable in this case?

That sounds acceptable to me @manuhabitela . It's probably a small diversion from the initial design, but an acceptable one in comparison to adding more code to support the red on hover.

**Comment by denniskigen** [comment]
> > We'd lose the "red on hover" style but I guess it's acceptable in this case?
> 
> That sounds acceptable to me @manuhabitela . It's probably a small diversion from the initial design, but an acceptable one in comparison to adding more code to support the red on hover.

Thanks for the sleuth work, @manuhabitela. Could you change the button `kind` to ghost so we can close this one out, @Vijaykv5?

**Comment by Vijaykv5** [comment]
Done @denniskigen

**Review by denniskigen — APPROVED** [review]

**Comment by denniskigen** [comment]
Thanks, all!

**Pull request merged**
