### PR TITLE
(feat) O3-2991, support Date type obs on the registration form

### PR DESCRIPTION
**Pull request by Michaelndula**
## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary
- Support Date type obs on the registration form

## Screenshots
dateObs

## Related Issue
- https://openmrs.atlassian.net/browse/O3-2991

@denniskigen @brandones

### CODE REVIEW

**Review by alaboso — COMMENTED** [review]
Does this support various locales and calendars?  Jewish, Ethiopian, Chinese?

**Review by kajambiya — APPROVED** [review]
LGTM

**Comment by brandones** [comment]
This code does not work. The value is not wired up correctly, so it never gets submitted. The date picker is rendered, but does nothing. This PR has introduced a new bug. @Michaelndula @kajambiya Please try to verify that PRs do not introduce bugs; in this case that would mean posting a video or screenshot demonstrating that the value actually gets submitted (either showing the value in the chart or showing the POST `/encounter` call in the network tab of the browser dev tools).

**Comment by Michaelndula** [comment]
Hi @brandones, I realised this and I am currently working on a solution to fix it.

**Pull request merged**
