### PR TITLE
(fix) O3-2781: Fix various aspects of the appointments summary table UI

### PR DESCRIPTION
**Pull request by usamaidrsk**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

This PR fixes the action button content alignment on appointments summary table

## Screenshots

image

## Other

[O3-2781](https://openmrs.atlassian.net/browse/O3-2781)

### CODE REVIEW

**Comment by denniskigen** [comment]
Is this still WIP? I only see changes to translations in the diff

**Comment by usamaidrsk** [comment]
> Is this still WIP? I only see changes to translations in the diff

I have updated the PR @denniskigen .
Thanks

**Comment by denniskigen** [comment]
State of things following my commit (which just fixes up a few more things):

https://github.com/openmrs/openmrs-esm-patient-management/assets/8509731/ed59e853-4336-4fd2-b476-0d2e5ae8d9ae

**Comment by denniskigen** [comment]
What still needs fixing is the `Actions` column. It some cases, we're rendering a button and in others, we're not. I'm not sure which designs this work was based off of, but we need to make stuff more standard there.

**Comment by usamaidrsk** [comment]
https://github.com/openmrs/openmrs-esm-patient-management/pull/956#issuecomment-1918762307

Yes it does @denniskigen 
Thanks

**Review by denniskigen — APPROVED** [review]
Thanks, @usamaidrsk!

**Pull request merged**
