### PR TITLE
(feat) O3-1686: Patient List information

### PR DESCRIPTION
**Pull request by Juliet-chime**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).
- [x] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
1. Added a section for patient information List
2. Created state value for checked item
3. Fixed the styling of buttons in patient list

### Link Ticket 
[https://issues.openmrs.org/browse/O3-1686?filter=-1&jql=project%20%3D%20O3%20AND%20iss[…]%20(EMPTY%2C%20currentUser())%20order%20by%20updated%20DESC](https://issues.openmrs.org/browse/O3-1686?filter=-1&jql=project%20%3D%20O3%20AND%20issuetype%20%3D%20Bug%20AND%20status%20%3D%20%22To%20Do%22%20AND%20resolution%20%3D%20Unresolved%20AND%20assignee%20in%20(EMPTY%2C%20currentUser())%20order%20by%20updated%20DESC)

## Screenshots
Screenshot (37)

*None.*

## Related Issue
[https://issues.openmrs.org/browse/O3-1686?filter=-1&jql=project%20%3D%20O3%20AND%20iss[…]%20(EMPTY%2C%20currentUser())%20order%20by%20updated%20DESC](https://issues.openmrs.org/browse/O3-1686?filter=-1&jql=project%20%3D%20O3%20AND%20issuetype%20%3D%20Bug%20AND%20status%20%3D%20%22To%20Do%22%20AND%20resolution%20%3D%20Unresolved%20AND%20assignee%20in%20(EMPTY%2C%20currentUser())%20order%20by%20updated%20DESC)

*None.*

## Other

*None.*

### CODE REVIEW

**Comment by vasharma05** [comment]
Please fill in the PR title, PR summary and correct issue ticket link. Please fill these details as they are mandatory.

**Review by Jexsie — COMMENTED** [review]
Hey @chimejuliet, thanks for this. Can please give us a summary of what you are doing and the issue ticket you working on?

**Comment by Juliet-chime** [comment]
> Please fill in the PR title, PR summary and correct issue ticket link. Please fill these details as they are mandatory.

done @vasharma05

**Comment by Juliet-chime** [comment]
> Please pull in the latest changes from main

@vasharma05 Done

**Review by vasharma05 — COMMENTED** [review]
Improvement

**Comment by vasharma05** [comment]
Where are you saving the fields selected from the dropdown @Juliet-chime ?

**Comment by Juliet-chime** [comment]
Thank you @Vineet, I have made the necessary changes

**Comment by Juliet-chime** [comment]
> Where are you saving the fields selected from the dropdown @Juliet-chime ?

I am saving the values in information state but I haven't added it to cohortDetails object, I tried adding information list value to cohort details object but got an error when submitting the '400 Bad Request'

Please what is the right way to pass in the values so the form submission is successfully

**Comment by vasharma05** [comment]
I'll look into this.

**Comment by hadijahkyampeire** [comment]
@Juliet-chime could you please make a rebase with the main and resolve the merge conflicts? Let me know if you need any help with that.

**Comment by Juliet-chime** [comment]
> @Juliet-chime could you please make a rebase with the main and resolve the merge conflicts? Let me know if you need any help with that.

@hadijahkyampeire I have fixed the merge conflict

**Comment by denniskigen** [comment]
@vasharma05 Is this feature still in line with the designs?

**Comment by denniskigen** [comment]
@ibacher, thoughts on the suitability of this change? It looks like the intention is to configure which columns and rows to render in the datatable.

**Pull request closed without merging**
