### PR TITLE
(feat) Show a locale-specific datepicker for Amharic and Tigrinya locales

### PR DESCRIPTION
**Pull request by kajambiya**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary

This PR wires up the Date of Birth field in the registration form to use the locale-aware [OpenmrsDatePicker](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-styleguide/src/datepicker/openmrs/openmrs-date-picker.component.tsx) component from Core. The OpenmrsDatePicker component is wired to render the default Carbon OpenMRS datepicker for all locales other than  `am` (Amharic), `am_ET` (Amharic Ethiopia), and `ti_ET` (Tigrinya Ethiopia). For these Ethiopic locales, a datepicker based on React Spectrum with support for the Ethiopic calendar is rendered instead.

### CODE REVIEW

**Review by ebambo — APPROVED** [review]
LGTM

**Comment by denniskigen** [comment]
You might need to tweak the calendar's z-index so the ContentSwitcher buttons don't get rendered above it:

CleanShot 2024-05-18 at 11  52 28@2x

**Comment by denniskigen** [comment]
Also, it looks like it defaults to the wrong date:

CleanShot 2024-05-18 at 11  55 06@2x

**Review by denniskigen — APPROVED** [review]
Thanks!

**Comment by kajambiya** [comment]
> Also, it looks like it defaults to the wrong date:
> 
> CleanShot 2024-05-18 at 11  55 06@2x

This will be fixed by the PR to core

**Pull request merged**
