### PR TITLE
fix: Broken pagination on the advanced patient search page

### PR DESCRIPTION
**Pull request by jnsereko**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).
- [x] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
Fixed broken pagination on the advanced patient search page 
cc @vasharma05  

## Screenshots

https://user-images.githubusercontent.com/58003327/235641120-0727f594-eb48-40b6-9681-564d011f8559.mov

## Related Issue

https://issues.openmrs.org/browse/O3-2068

## Other

*None.*

### CODE REVIEW

**Review by vasharma05 — APPROVED** [review]
Thanks for the fix @jnsereko !

Please confirm the fix after the merge and try running all the required use cases.

**Comment by vasharma05** [comment]
Hi @jnsereko !
There's a fallback in the pagination.

Use case: Search 10 and go into advanced patient search. Then go to page > 2. After going to that page, try searching for "Joshua". You'll see that it needs to revert back to 1st page. In the image below, there are 2 search results, but since the page number is the prev page page, it shows no results.

image

**Comment by vasharma05** [comment]
Reverting the PR for now.

**Comment by jnsereko** [comment]
> Hi @jnsereko ! There's a fallback in the pagination.
> 
> Use case: Search 10 and go into advanced patient search. Then go to page > 2. After going to that page, try searching for "Joshua". You'll see that it needs to revert back to 1st page. In the image below, there are 2 search results, but since the page number is the prev page page, it shows no results.
> 
> image

this happens because when you change to page 2, the lower and upper boundary gets pushed to 5 and 10 respectively and if the search term returns results below 10, ie 2, pagination logic will try to return the second page of the 2 results hence returning an empty list 

We just need to push the user to the first page each time the search query changes.
Unfortunately, `useEffect` hook pushes the user to the first page regardless of whether the search query changes or not.
Possible solution is to use `useRef` to tack each time the query changes and push the user to the first page.

something like 
```
  const prevQuery = useRef<string>();

  if (prevQuery.current !== query) {
    prevQuery.current = query;
    goto(1);
  }
```

**Pull request merged**
