### PR TITLE
O3-1668:Fix Type-fields in Search

### PR DESCRIPTION
**Pull request by jwnasambu**
## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

Fixed the DOB, Age, Phone and Postcode fields to display the required information on running advanced search.

## Screenshots

https://user-images.githubusercontent.com/33891016/215790041-898a4b57-11fd-44b8-858a-e8024241f0dd.mp4

## Related Issue

*None.*

## Other

*None.*

### CODE REVIEW

**Comment by vasharma05** [comment]
Please put the issue's link in the PR description.
Thanks!

**Comment by vasharma05** [comment]
Hi @jwnasambu, 
This is an issue that I'm looking into, but this is not the correct fix. Also, just commenting the ref is not the right way to move ahead with. You should try to understand what the piece of code is doing and try to fix the issue instead of looking for a quick fix

**Comment by jwnasambu** [comment]
@vasharma05 Thanks so so much for the proposed way forward

**Comment by jwnasambu** [comment]
You are right @vasharma05. Commenting out just come in as a way of debugging besides, I should have just deleted it out instead of commenting out just incase it was the correct way of fixing it.

**Comment by denniskigen** [comment]
Hey @jwnasambu and @vasharma05, am I correct in thinking that this issue got resolved? If so, please feel free to close this PR. Thanks!

**Comment by jwnasambu** [comment]
@denniskigen you are right. Let us close this PR and if possible delete it

**Pull request closed without merging**
