### PR TITLE
(refactor) O3-2815: Replace usages of `/ws/rest/v1` with `restBaseUrl`

### PR DESCRIPTION
**Pull request by himanshu-malviya15**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary
Replaced all the instances of /ws/rest/v1 with restBaseUrl from framework

## Related Issue
[O3-2815](https://openmrs.atlassian.net/jira/software/c/projects/O3/issues/O3-2815)

### CODE REVIEW

**Comment by jwnasambu** [comment]
@himanshu-malviya15 kindly do not change the strings in mocks or test files at all.

**Comment by brandones** [comment]
@jwnasambu Why?

**Comment by himanshu-malviya15** [comment]
> @himanshu-malviya15 following #935, please review your work to ensure that there's a trailing slash after each usage of `restBaseUrl`.

@denniskigen Please review it is done

**Review by denniskigen — APPROVED** [review]
Great work, @himanshu-malviya15! Thanks

**Pull request merged**
