### PR TITLE
(chore) Release v7.0.0

### PR DESCRIPTION
**Pull request by vasharma05**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary
This PR bumps the `@openmrs/esm-framework` and cuts a major release for patient management.

## Screenshots
None

## Related Issue
None

### CODE REVIEW

**Review by NethmiRodrigo — COMMENTED** [review]
Should we update yarn as well @vasharma05?

**Comment by denniskigen** [comment]
Done, @NethmiRodrigo.

**Review by NethmiRodrigo — APPROVED** [review]
LGTM, thanks @denniskigen @vasharma05!

**Comment by denniskigen** [comment]
Thanks!

**Pull request merged**
