### PR TITLE
O3-1891: use sessionStorage instead of localStorage for searchReturnUrl

### PR DESCRIPTION
**Pull request by Jexsie**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [x] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

   Changed SearchReturnUrl storage from localStorage to sessionStorage as adviced by @ibacher  [here](https://issues.openmrs.org/browse/O3-1891)

## Screenshots

*None.*

## Related Issue
*None.*

## Other

*None.*

### CODE REVIEW

**Comment by Jexsie** [comment]
Kindly requesting review and advice here @ibacher .

**Comment by jnsereko** [comment]
Thanks @Jexsie for this.   Push an empty commit to rerun the build.

**Review by jnsereko — CHANGES_REQUESTED** [review]
thanks @jexsie for working on this.  Remove the changes from the yarn.lock file to fix the build

**Comment by Jexsie** [comment]
> thanks @Jexsie for working on this. Remove the changes from the yarn.lock file to fix the build cc @denniskigen

Finished. Successfully reverted the changes in the yarn.lock file

**Comment by jnsereko** [comment]
> > thanks @Jexsie for working on this. Remove the changes from the yarn.lock file to fix the build cc @denniskigen
> 
> Finished. Successfully reverted the changes in the yarn.lock file

push an empty commit to trigger the build

**Comment by ibacher** [comment]
@jnsereko:

> push an empty commit to trigger the build

While this works for PRs from previous contributors and those with a dev level, first-time contributors builds are held until someone approves them (GitHub's rule, not ours).

**Pull request merged**
