### PR TITLE
(fix) O3-2730 - Back button aligned in appointments calendar

### PR DESCRIPTION
**Pull request by Vijaykv5**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

Back button well aligned by removing `<div className={styles.backButton}>` and its corresponding css properties.
## Screenshots

> Before :

Screenshot 2024-01-14 at 11 44 32 AM

> After : 

Screenshot 2024-01-14 at 11 45 19 AM

## Related Issue

 [O3-2730 ](https://openmrs.atlassian.net/browse/O3-2730)

### CODE REVIEW

**Comment by Vijaykv5** [comment]
@denniskigen May you can review this PR

**Comment by Vijaykv5** [comment]
@denniskigen @vasharma05 @jwamalwa @pirupius 
May you can review this PR please?

**Comment by vasharma05** [comment]
@usamaidrsk , can you review this PR?
Thanks!

**Comment by jwnasambu** [comment]
@Vijaykv5 basing on the design provided this LGTM!

**Comment by usamaidrsk** [comment]
> @usamaidrsk , can you review this PR? Thanks!

LGTM, Thanks @Vijaykv5 
cc @vasharma05

**Review by pirupius — APPROVED** [review]

**Pull request merged**
